# Spring Configs
spring:
  application:
    name: @project.artifactId@
  main:
    banner-mode: off
    web-application-type: none
  ai:
    mcp:
      server:
        enabled: true
        stdio: true
        name: @project.artifactId@
        version: @project.version@
        instructions: "@project.description@"
        type: SYNC #ASYNC
        request-timeout: 30
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false

# Logging
logging:
  register-shutdown-hook: false
  console:
    enabled: false
  file:
    name: pihole-mcp-stdio-server.log

# Pihole Server
pihole:
  protocol: ${PIHOLE_PROTOCOL:http}
  port: ${PIHOLE_PORT:80}
  url: ${pihole.protocol}://${PIHOLE_HOST}:${pihole.port}/api/
  app_password: ${PIHOLE_APP_PASSWORD}
